<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NMSLAP139" failures="0" tests="9" name="org.com.TestNG.TestNGALLProgram" time="41.351" errors="1" timestamp="2022-02-22T16:30:44 IST" skipped="0">
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="Flipkart" time="14.155"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="PVR" time="3.265"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="Adctin" time="7.103"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="Airtel" time="0.000">
    <error message="
Method private void org.com.TestNG.TestNGALLProgram.Airtel(java.lang.String) requires a @DataProvider named : txtMobile" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method private void org.com.TestNG.TestNGALLProgram.Airtel(java.lang.String) requires a @DataProvider named : txtMobile
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Airtel -->
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="PVR" time="2.512"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="Facebook" time="4.563"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="Amazon" time="5.418"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="PVR" time="2.101"/>
  <system-out/>
  <testcase classname="org.com.TestNG.TestNGALLProgram" name="BookmyShow" time="2.234"/>
  <system-out/>
</testsuite> <!-- org.com.TestNG.TestNGALLProgram -->
